### ISSUE TITLE
Functions with parameters on multiple lines aren't highlighted correctly?

### ISSUE THREAD

**Issue by JHDeerin** [Entomy/Ada-vscode#22]
![functionHighlightingBug](https://user-images.githubusercontent.com/22411098/58273486-d4142a80-7d5e-11e9-9911-0a134edd3064.png)

Relevant code snippet causing problems:

```Ada
function goodHighlight(p1 : Integer; p2 : Integer) return Integer;

-- Function name isn't highlighted blue, and the last parameter (p3) isn't
-- highlighted at all?
function badHighlight(p1 : Integer;
                      p2 : Integer;
                      p3 : Integer) return Integer;

-- If we add a semicolon at the end, though, p3 is highlighted correctly:
function badHighlight2(p1 : Integer;
                       p2 : Integer;
                       p3 : Integer;) return Integer;
```

**Comment by Entomy** [comment]
Yeah I'm well aware. This is either due to a deficiency in Regex, or there's some trick I'm not aware of.

If I use a start="" end="" for the match it is too greedy and consumes way more than it should, breaking far more things.

Unless someone knows the Regex for this, I'm considering it LSP Required

**Comment by Entomy** [comment]
This isn't LSP required. I've got it working in the new rewrite.
![image](https://user-images.githubusercontent.com/25399505/60191996-369b9300-9803-11e9-9549-e42301905527.png)

I gotta get up to feature parity, then it'll be pushed to the VS Code Marketplace.
