### ISSUE TITLE
Argument blocks cannot be nested

### ISSUE THREAD

**Issue by wtok** [Entomy/Ada-vscode#8]
It seems that everything after a close-paren in an assert pragma is highlighted red until another set of parens is opened. After that set closes, it's red again.

This applies to parenthesised expressions, function calls, array accesses, etc. It seems that only numbers and letters are affected, so symbols like `=` are fine, but numbers, variable names, strings and operators like `in`, `not in`, `and then`, etc will show up red.

![image](https://user-images.githubusercontent.com/10289860/55767295-6914da00-5ab7-11e9-8ea3-768bc8e9713a.png)

**Comment by Entomy** [comment]
![image](https://user-images.githubusercontent.com/25399505/55767536-4945cd80-5a47-11e9-9196-93b474812cdd.png)

dafuq?

**Comment by Entomy** [comment]
![image](https://user-images.githubusercontent.com/25399505/55767964-f240f800-5a48-11e9-928c-d90b7cc1c9de.png)

This is an issue with any arguments block containing another arguments block. The error text happens because I've defined a pattern for matching non-defined pragmas as invalid to help catch spelling errors. As such, I'm renaming the issue.

**Comment by Entomy** [comment]
![image](https://user-images.githubusercontent.com/25399505/55768606-890eb400-5a4b-11e9-9087-94afc8f2b114.png)

Should be fixed, reopen if necessary. (I've got a few argument related errors to fix then I'll publish this update)

**Comment by wtok** [comment]
It looks like `16#cafe_f00d#` isn't completely highlighted as a number in that screenshot.

**Comment by Entomy** [comment]
"(I've got a few argument related errors to fix then I'll publish this update)", yeah, that's one of those.
